# postgresql:
#     enabled: false

# externalPostgresql:
#   host: postgresql.team10.svc.cluster.local
#   username: sentry
#   password: sentry

sentry:
  worker:
    replicas: 1

redis:
  architecture: 'standalone'

rabbitmq:
  replicaCount: 1
  rbac:
    create: false
  pdb:
    create: false

# kafka:
#   enabled: false

# externalKafka:
#   host: tb-kafka.team10.svc.cluster.local
