apiVersion: v1
entries:
  sentry:
  - apiVersion: v2
    appVersion: 21.8.0
    created: "2021-12-03T18:12:12.812802+03:00"
    description: A Helm chart for Kubernetes
    digest: 97348d96e58c9afc50df3d07c6a6b95ea6029e8c2d35b3a88e6826587ab3063c
    name: sentry
    type: application
    urls:
    - https://raw.githubusercontent.com/waffleboot/sentry/main/charts/sentry-12.0.0.tgz
    version: 12.0.0
generated: "2021-12-03T18:12:12.809053+03:00"
