apiVersion: v1
entries:
  sentry:
  - apiVersion: v2
    appVersion: 21.8.0
    created: "2021-12-03T18:36:23.409795+03:00"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: A Helm chart for Kubernetes
    digest: aa3230fd95a0af9a14d37a61be0571392483542b5c14836308fbd5df74c657e5
    name: sentry
    type: application
    urls:
    - https://raw.githubusercontent.com/waffleboot/sentry/main/charts/sentry-12.0.0.tgz
    version: 12.0.0
generated: "2021-12-03T18:36:23.384873+03:00"
