apiVersion: v1
entries:
  sentry:
  - apiVersion: v2
    appVersion: 21.8.0
    created: "2021-12-03T21:15:28.001422+03:00"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 12.0.0
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://sentry-kubernetes.github.io/charts
      version: 3.0.0
    - alias: rabbitmq
      condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.1
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.2.4
    - condition: nginx.enabled
      name: nginx
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.3
    description: A Helm chart for Kubernetes
    digest: 38adb7138f74676a58ba216feba1ea2d804d2e13fab24725975819ca40cc422c
    name: sentry
    type: application
    urls:
    - https://raw.githubusercontent.com/waffleboot/sentry/main/charts/sentry-12.0.0.tgz
    version: 12.0.0
generated: "2021-12-03T21:15:27.948358+03:00"
