apiVersion: v1
entries:
  sentry:
  - apiVersion: v2
    appVersion: 21.8.0
    created: "2021-12-04T03:14:16.735165+03:00"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 12.0.0
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://sentry-kubernetes.github.io/charts
      version: 3.0.0
    - alias: rabbitmq
      condition: rabbitmq.enabled
      name: rabbitmq
      repository: https://charts.bitnami.com/bitnami
      version: 8.9.1
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.2.4
    - condition: nginx.enabled
      name: nginx
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.3
    description: A Helm chart for Kubernetes
    digest: 4a004172174e4290b4ae8afbb6016761c809b25ca5fa410b3df9ab805fa05416
    name: sentry
    type: application
    urls:
    - https://raw.githubusercontent.com/waffleboot/sentry/fix/charts/sentry-12.0.0.tgz
    version: 12.0.0
generated: "2021-12-04T03:14:16.683105+03:00"
