---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-simple
  labels:
    app: {{ .Release.Name }}-simple
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-simple
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-simple
    spec:
      containers:
        - name: {{ .Release.Name }}-simple
          resources:
            limits:
              memory: 64Mi
              cpu: "100m"
            requests:
              memory: 64Mi
              cpu: "30m"
          image: busybox
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity
